import tinto from "@/assets/bottle-tinto.jpg";
import blanco from "@/assets/bottle-blanco.jpg";
import rosado from "@/assets/bottle-rosado.jpg";
import reserva from "@/assets/bottle-reserva.jpg";

// Catálogo generado automáticamente a partir de la Tarifa Profesional de Vinos.
// Precios profesionales (IVA no incluido), para hostelería y alimentación.

export type WineCategory = "Tinto" | "Blanco" | "Rosado" | "Espumoso" | "Otros";

export interface Wine {
  slug: string;
  name: string;
  bodega: string | null;
  location: string | null;
  region: string;
  category: WineCategory;
  price: number | null;
  note: string | null;
}

export const WINES: Wine[] = [
  {
    slug: "pago-calzadilla-opta",
    name: "Opta",
    bodega: "PAGO CALZADILLA",
    location: "Huete / Cuenca",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 8.4,
    note: null,
  },
  {
    slug: "pago-calzadilla-calzadilla-classic",
    name: "Calzadilla Classic",
    bodega: "PAGO CALZADILLA",
    location: "Huete / Cuenca",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 11.85,
    note: null,
  },
  {
    slug: "pago-calzadilla-calzadilla-allegro",
    name: "Calzadilla Allegro",
    bodega: "PAGO CALZADILLA",
    location: "Huete / Cuenca",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 13.95,
    note: null,
  },
  {
    slug: "pago-calzadilla-gran-calzadilla",
    name: "Gran Calzadilla",
    bodega: "PAGO CALZADILLA",
    location: "Huete / Cuenca",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 27.5,
    note: null,
  },
  {
    slug: "pago-campo-de-la-guardia-martue",
    name: "Martúe",
    bodega: "PAGO CAMPO DE LA GUARDIA",
    location: "La Guardia / Toledo",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 5.5,
    note: "10% en mercancía",
  },
  {
    slug: "pago-campo-de-la-guardia-martue-especial",
    name: "Martúe Especial",
    bodega: "PAGO CAMPO DE LA GUARDIA",
    location: "La Guardia / Toledo",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 9.5,
    note: null,
  },
  {
    slug: "pago-campo-de-la-guardia-martue-chardonnay",
    name: "Martúe Chardonnay",
    bodega: "PAGO CAMPO DE LA GUARDIA",
    location: "La Guardia / Toledo",
    region: "VINOS DE PAGO",
    category: "Blanco",
    price: 7.65,
    note: null,
  },
  {
    slug: "pago-vallegarcia-petit-hipperia",
    name: "Petit Hipperia",
    bodega: "PAGO VALLEGARCÍA",
    location: "Retuerta del Bullaque / Ciudad Real",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 11.1,
    note: null,
  },
  {
    slug: "pago-vallegarcia-vallegarcia-syrah",
    name: "Vallegarcía Syrah",
    bodega: "PAGO VALLEGARCÍA",
    location: "Retuerta del Bullaque / Ciudad Real",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 17.35,
    note: null,
  },
  {
    slug: "pago-vallegarcia-vallegarcia-viognier",
    name: "Vallegarcía Viognier",
    bodega: "PAGO VALLEGARCÍA",
    location: "Retuerta del Bullaque / Ciudad Real",
    region: "VINOS DE PAGO",
    category: "Blanco",
    price: 17.35,
    note: null,
  },
  {
    slug: "pago-finca-rio-negro-992-de-finca-rio-negro",
    name: "992 de Finca Río Negro",
    bodega: "PAGO FINCA RÍO NEGRO",
    location: "Cogolludo / Guadalajara",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 7.25,
    note: null,
  },
  {
    slug: "pago-finca-rio-negro-finca-rio-negro-crianza",
    name: "Finca Río Negro Crianza",
    bodega: "PAGO FINCA RÍO NEGRO",
    location: "Cogolludo / Guadalajara",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 10.9,
    note: null,
  },
  {
    slug: "pago-finca-rio-negro-finca-rio-negro-cerro-del-lobo",
    name: "Finca Río Negro Cerro del Lobo",
    bodega: "PAGO FINCA RÍO NEGRO",
    location: "Cogolludo / Guadalajara",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 17.45,
    note: null,
  },
  {
    slug: "pago-finca-rio-negro-finca-rio-negro-5o-ano",
    name: "Finca Río Negro 5º Año",
    bodega: "PAGO FINCA RÍO NEGRO",
    location: "Cogolludo / Guadalajara",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 20.15,
    note: null,
  },
  {
    slug: "pago-finca-rio-negro-finca-rio-negro-gewurztraminer",
    name: "Finca Río Negro Gewürztraminer",
    bodega: "PAGO FINCA RÍO NEGRO",
    location: "Cogolludo / Guadalajara",
    region: "VINOS DE PAGO",
    category: "Blanco",
    price: 9.2,
    note: null,
  },
  {
    slug: "pago-abadia-retuerta-abadia-retuerta-seleccion-especial",
    name: "Abadía Retuerta Selección Especial",
    bodega: "PAGO ABADÍA RETUERTA",
    location: "Sardón de Duero / Valladolid",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 22.5,
    note: null,
  },
  {
    slug: "pago-abadia-retuerta-abadia-retuerta-cuvee-palomar",
    name: "Abadía Retuerta Cuvee Palomar",
    bodega: "PAGO ABADÍA RETUERTA",
    location: "Sardón de Duero / Valladolid",
    region: "VINOS DE PAGO",
    category: "Espumoso",
    price: 30.95,
    note: null,
  },
  {
    slug: "pago-abadia-retuerta-abadia-retuerta-petit-verdot",
    name: "Abadía Retuerta Petit Verdot",
    bodega: "PAGO ABADÍA RETUERTA",
    location: "Sardón de Duero / Valladolid",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 97.0,
    note: null,
  },
  {
    slug: "pago-abadia-retuerta-abadia-retuerta-pago-garduna",
    name: "Abadía Retuerta Pago Garduña",
    bodega: "PAGO ABADÍA RETUERTA",
    location: "Sardón de Duero / Valladolid",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 68.0,
    note: null,
  },
  {
    slug: "pago-abadia-retuerta-abadia-retuerta-pago-valdebellon",
    name: "Abadía Retuerta Pago Valdebellón",
    bodega: "PAGO ABADÍA RETUERTA",
    location: "Sardón de Duero / Valladolid",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 61.25,
    note: null,
  },
  {
    slug: "pago-abadia-retuerta-abadia-retuerta-le-domaine",
    name: "Abadía Retuerta Le Domaine",
    bodega: "PAGO ABADÍA RETUERTA",
    location: "Sardón de Duero / Valladolid",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 32.8,
    note: "Consultar",
  },
  {
    slug: "pago-finca-elez-finca-elez-chardonnay",
    name: "Finca Élez Chardonnay",
    bodega: "PAGO FINCA ÉLEZ",
    location: "El Bonillo / Albacete",
    region: "VINOS DE PAGO",
    category: "Blanco",
    price: 14.25,
    note: null,
  },
  {
    slug: "pago-finca-elez-finca-elez-syrah",
    name: "Finca Élez Syrah",
    bodega: "PAGO FINCA ÉLEZ",
    location: "El Bonillo / Albacete",
    region: "VINOS DE PAGO",
    category: "Tinto",
    price: 14.25,
    note: null,
  },
  {
    slug: "pago-finca-elez-finca-elez-miracielos-cabernet-sauvignon",
    name: "Finca Élez Miracielos Cabernet Sauvignon",
    bodega: "PAGO FINCA ÉLEZ",
    location: "El Bonillo / Albacete",
    region: "VINOS DE PAGO",
    category: "Blanco",
    price: 16.95,
    note: null,
  },
  {
    slug: "bodegas-tintoralba-tintoralba-cerro-del-buey",
    name: "Tintoralba Cerro del Buey",
    bodega: "BODEGAS TINTORALBA",
    location: "La Higueruela / Albacete",
    region: "ALMANSA",
    category: "Tinto",
    price: 5.95,
    note: null,
  },
  {
    slug: "bodegas-tintoralba-tintoralba-alqueria-de-la-granja",
    name: "Tintoralba Alquería de La Granja",
    bodega: "BODEGAS TINTORALBA",
    location: "La Higueruela / Albacete",
    region: "ALMANSA",
    category: "Tinto",
    price: 9.75,
    note: null,
  },
  {
    slug: "bodegas-tintoralba-tintoralba-blanc-de-noirs",
    name: "Tintoralba Blanc de Noirs",
    bodega: "BODEGAS TINTORALBA",
    location: "La Higueruela / Albacete",
    region: "ALMANSA",
    category: "Blanco",
    price: 9.4,
    note: null,
  },
  {
    slug: "bodegas-atalaya-laya",
    name: "Laya",
    bodega: "BODEGAS ATALAYA",
    location: "Almansa / Albacete",
    region: "ALMANSA",
    category: "Tinto",
    price: 4.0,
    note: null,
  },
  {
    slug: "bodegas-atalaya-la-atalaya",
    name: "La Atalaya",
    bodega: "BODEGAS ATALAYA",
    location: "Almansa / Albacete",
    region: "ALMANSA",
    category: "Tinto",
    price: 8.45,
    note: null,
  },
  {
    slug: "bodegas-atalaya-el-vigia-de-la-atalaya",
    name: "El Vigía de la Atalaya",
    bodega: "BODEGAS ATALAYA",
    location: "Almansa / Albacete",
    region: "ALMANSA",
    category: "Tinto",
    price: 4.0,
    note: null,
  },
  {
    slug: "bodegas-atalaya-alaya-tierra",
    name: "Alaya Tierra",
    bodega: "BODEGAS ATALAYA",
    location: "Almansa / Albacete",
    region: "ALMANSA",
    category: "Tinto",
    price: 16.75,
    note: null,
  },
  {
    slug: "bodegas-dominio-de-tares-cepas-viejas",
    name: "Cepas Viejas",
    bodega: "BODEGAS DOMINIO DE TARES",
    location: "San Román de Bembibre / León",
    region: "BIERZO",
    category: "Tinto",
    price: 11.99,
    note: null,
  },
  {
    slug: "bodegas-martin-codax-cuatro-pasos",
    name: "Cuatro Pasos",
    bodega: "BODEGAS MARTÍN CÓDAX",
    location: "Cacabelos / León",
    region: "BIERZO",
    category: "Tinto",
    price: 4.75,
    note: null,
  },
  {
    slug: "bodegas-emilio-moro-bestizo",
    name: "Bestizo",
    bodega: "BODEGAS EMILIO MORO",
    location: "Ponferrada / León",
    region: "BIERZO",
    category: "Tinto",
    price: 11.5,
    note: null,
  },
  {
    slug: "bodegas-emilio-moro-polvorete-godello",
    name: "Polvorete Godello",
    bodega: "BODEGAS EMILIO MORO",
    location: "Ponferrada / León",
    region: "BIERZO",
    category: "Blanco",
    price: 7.75,
    note: null,
  },
  {
    slug: "bodegas-emilio-moro-el-zarzal-godello",
    name: "El Zarzal Godello",
    bodega: "BODEGAS EMILIO MORO",
    location: "Ponferrada / León",
    region: "BIERZO",
    category: "Blanco",
    price: 11.41,
    note: null,
  },
  {
    slug: "bodegas-emilio-moro-la-revelia-godello",
    name: "La Revelía Godello",
    bodega: "BODEGAS EMILIO MORO",
    location: "Ponferrada / León",
    region: "BIERZO",
    category: "Blanco",
    price: 18.91,
    note: null,
  },
  {
    slug: "bodegas-ateca-honoro-vera",
    name: "Honoro Vera",
    bodega: "BODEGAS ATECA",
    location: "Ateca / Zaragoza",
    region: "CALATAYUD",
    category: "Tinto",
    price: 4.0,
    note: null,
  },
  {
    slug: "bodegas-ateca-atteca",
    name: "Atteca",
    bodega: "BODEGAS ATECA",
    location: "Ateca / Zaragoza",
    region: "CALATAYUD",
    category: "Tinto",
    price: 8.5,
    note: null,
  },
  {
    slug: "bodegas-san-alejandro-baltasar-gracian-vinas-viejas",
    name: "Baltasar Gracián Viñas Viejas",
    bodega: "BODEGAS SAN ALEJANDRO",
    location: "Ateca / Zaragoza",
    region: "CALATAYUD",
    category: "Tinto",
    price: 6.5,
    note: null,
  },
  {
    slug: "bodegas-san-alejandro-clos-baltasar",
    name: "Clos Baltasar",
    bodega: "BODEGAS SAN ALEJANDRO",
    location: "Ateca / Zaragoza",
    region: "CALATAYUD",
    category: "Tinto",
    price: 9.5,
    note: null,
  },
  {
    slug: "bodegas-morca-flor-de-morca",
    name: "Flor de Morca",
    bodega: "BODEGAS MORCA",
    location: "Borja / Zaragoza",
    region: "CAMPO DE BORJA",
    category: "Tinto",
    price: 5.5,
    note: null,
  },
  {
    slug: "cesar-principe-clarete-de-luna",
    name: "Clarete de Luna",
    bodega: "CÉSAR PRÍNCIPE",
    location: "Fuensaldaña / Valladolid",
    region: "CIGALES",
    category: "Rosado",
    price: 4.0,
    note: null,
  },
  {
    slug: "cesar-principe-13-cantaros-nicolas",
    name: "13 Cántaros Nicolás",
    bodega: "CÉSAR PRÍNCIPE",
    location: "Fuensaldaña / Valladolid",
    region: "CIGALES",
    category: "Tinto",
    price: 5.5,
    note: null,
  },
  {
    slug: "cesar-principe-cesar-principe",
    name: "César Príncipe",
    bodega: "CÉSAR PRÍNCIPE",
    location: "Fuensaldaña / Valladolid",
    region: "CIGALES",
    category: "Tinto",
    price: 16.85,
    note: null,
  },
  {
    slug: "casa-castillo-casa-castillo-monastrell",
    name: "Casa Castillo Monastrell",
    bodega: "CASA CASTILLO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 6.75,
    note: null,
  },
  {
    slug: "casa-castillo-casa-castillo-valtosca",
    name: "Casa Castillo Valtosca",
    bodega: "CASA CASTILLO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 14.5,
    note: null,
  },
  {
    slug: "casa-castillo-casa-castillo-el-molar",
    name: "Casa Castillo El Molar",
    bodega: "CASA CASTILLO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 14.0,
    note: null,
  },
  {
    slug: "casa-castillo-casa-castillo-la-tendida",
    name: "Casa Castillo La Tendida",
    bodega: "CASA CASTILLO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 11.15,
    note: null,
  },
  {
    slug: "casa-castillo-casa-castillo-las-gravas",
    name: "Casa Castillo Las Gravas",
    bodega: "CASA CASTILLO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 32.5,
    note: null,
  },
  {
    slug: "casa-castillo-casa-castillo-pie-franco",
    name: "Casa Castillo Pie Franco",
    bodega: "CASA CASTILLO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 90.5,
    note: null,
  },
  {
    slug: "juan-gil-juan-gil-amarilla",
    name: "Juan Gil Amarilla",
    bodega: "JUAN GIL",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 4.25,
    note: null,
  },
  {
    slug: "juan-gil-juan-gil-plata",
    name: "Juan Gil Plata",
    bodega: "JUAN GIL",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 7.95,
    note: null,
  },
  {
    slug: "juan-gil-juan-gil-azul",
    name: "Juan Gil Azul",
    bodega: "JUAN GIL",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 17.25,
    note: null,
  },
  {
    slug: "juan-gil-juan-gil-blanco-moscatel",
    name: "Juan Gil Blanco Moscatel",
    bodega: "JUAN GIL",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Blanco",
    price: 4.5,
    note: null,
  },
  {
    slug: "bodegas-el-nido-clio",
    name: "Clio",
    bodega: "BODEGAS EL NIDO",
    location: "Jumilla / Murcia",
    region: "JUMILLA",
    category: "Tinto",
    price: 26.85,
    note: null,
  },
  {
    slug: "martin-codax-mara-martin-godello",
    name: "Mara Martín Godello",
    bodega: "MARTÍN CODAX",
    location: "Monterrei / Orense",
    region: "MONTERREI",
    category: "Blanco",
    price: 6.25,
    note: null,
  },
  {
    slug: "bodega-martin-codax-alba-de-martin-codax",
    name: "Alba de Martín Códax",
    bodega: "BODEGA MARTÍN CÓDAX",
    location: "Cambados / Pontevedra",
    region: "RÍAS BAIXAS",
    category: "Tinto",
    price: 6.5,
    note: null,
  },
  {
    slug: "bodega-martin-codax-martin-codax",
    name: "Martín Códax",
    bodega: "BODEGA MARTÍN CÓDAX",
    location: "Cambados / Pontevedra",
    region: "RÍAS BAIXAS",
    category: "Tinto",
    price: 8.5,
    note: null,
  },
  {
    slug: "bodega-pazo-de-barrantes-pazo-de-barrantes",
    name: "Pazo de Barrantes",
    bodega: "BODEGA PAZO de BARRANTES",
    location: "Barrantes / Pontevedra",
    region: "RÍAS BAIXAS",
    category: "Tinto",
    price: 27.0,
    note: null,
  },
  {
    slug: "bodega-pazo-de-barrantes-la-comtesse",
    name: "La Comtesse",
    bodega: "BODEGA PAZO de BARRANTES",
    location: "Barrantes / Pontevedra",
    region: "RÍAS BAIXAS",
    category: "Tinto",
    price: 80.0,
    note: null,
  },
  {
    slug: "bodega-terras-gauda-terras-gaudas",
    name: "Terras Gaudas",
    bodega: "BODEGA TERRAS GAUDA",
    location: "O Rosal / Pontevedra",
    region: "RÍAS BAIXAS",
    category: "Tinto",
    price: 10.75,
    note: null,
  },
  {
    slug: "bodega-nora-nora",
    name: "Nora",
    bodega: "BODEGA NORA",
    location: "As Neves / Pontevedra",
    region: "RÍAS BAIXAS",
    category: "Tinto",
    price: 9.7,
    note: null,
  },
  {
    slug: "vina-mein-emilio-rojo-alma-carraovejas-mein",
    name: "Mein",
    bodega: "VIÑA MEIN / EMILIO ROJO -ALMA CARRAOVEJAS-",
    location: "Leiro / Orense",
    region: "RIBEIRO",
    category: "Tinto",
    price: 13.75,
    note: null,
  },
  {
    slug: "vina-mein-emilio-rojo-alma-carraovejas-o-gran-mein",
    name: "O Gran Mein",
    bodega: "VIÑA MEIN / EMILIO ROJO -ALMA CARRAOVEJAS-",
    location: "Leiro / Orense",
    region: "RIBEIRO",
    category: "Tinto",
    price: 20.5,
    note: null,
  },
  {
    slug: "bodega-a-vilerma-jose-pariente-a-vilerma",
    name: "A Vilerma",
    bodega: "BODEGA A VILERMA --JOSÉ PARIENTE-",
    location: "Leiro / Orense",
    region: "RIBEIRO",
    category: "Tinto",
    price: 8.95,
    note: null,
  },
  {
    slug: "bodega-martin-codax-anxo-martin",
    name: "Anxo Martín",
    bodega: "BODEGA MARTÍN CÓDAX",
    location: null,
    region: "RIBEIRO",
    category: "Tinto",
    price: 7.75,
    note: null,
  },
  {
    slug: "emilio-moro-finca-resalso",
    name: "Finca Resalso",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 6.94,
    note: null,
  },
  {
    slug: "emilio-moro-finca-resalso-magnum",
    name: "Finca Resalso Magnum",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 14.58,
    note: null,
  },
  {
    slug: "emilio-moro-emilio-moro-50-cl",
    name: "Emilio Moro 50 cl.",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 9.55,
    note: null,
  },
  {
    slug: "emilio-moro-emilio-moro",
    name: "Emilio Moro",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 14.88,
    note: null,
  },
  {
    slug: "emilio-moro-emilio-moro-magnum",
    name: "Emilio Moro Magnum",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 31.25,
    note: null,
  },
  {
    slug: "emilio-moro-la-felisa",
    name: "La Felisa",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 18.51,
    note: null,
  },
  {
    slug: "emilio-moro-malleolus",
    name: "Malleolus",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 25.12,
    note: null,
  },
  {
    slug: "emilio-moro-malleolus-magnum",
    name: "Malleolus Magnum",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 52.76,
    note: null,
  },
  {
    slug: "emilio-moro-malleolus-de-valderramiro",
    name: "Malleolus de Valderramiro",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 69.5,
    note: null,
  },
  {
    slug: "emilio-moro-malleolus-de-sanchomartin",
    name: "Malleolus de Sanchomartín",
    bodega: "EMILIO MORO",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 95.9,
    note: null,
  },
  {
    slug: "protos-protos-roble",
    name: "Protos Roble",
    bodega: "PROTOS",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 6.1,
    note: null,
  },
  {
    slug: "protos-protos-9-meses",
    name: "Protos 9 meses",
    bodega: "PROTOS",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 7.65,
    note: null,
  },
  {
    slug: "protos-protos-crianza",
    name: "Protos Crianza",
    bodega: "PROTOS",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 12.55,
    note: "3º año",
  },
  {
    slug: "protos-protos-reserva",
    name: "Protos Reserva",
    bodega: "PROTOS",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 19.3,
    note: "5º año",
  },
  {
    slug: "protos-protos-27",
    name: "Protos 27",
    bodega: "PROTOS",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 15.3,
    note: null,
  },
  {
    slug: "protos-carroa",
    name: "Carroa",
    bodega: "PROTOS",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 24.3,
    note: null,
  },
  {
    slug: "aalto-aalto",
    name: "Aalto",
    bodega: "AALTO",
    location: "Quintanilla de Arriba / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 27.25,
    note: null,
  },
  {
    slug: "aalto-aalto-ps",
    name: "Aalto PS",
    bodega: "AALTO",
    location: "Quintanilla de Arriba / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 64.5,
    note: null,
  },
  {
    slug: "alonso-del-yerro-alonso-del-yerro",
    name: "Alonso del Yerro",
    bodega: "ALONSO DEL YERRO",
    location: "Roa / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 19.75,
    note: null,
  },
  {
    slug: "alonso-del-yerro-maria-de-alonso-del-yerro",
    name: "María de Alonso del Yerro",
    bodega: "ALONSO DEL YERRO",
    location: "Roa / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 49.75,
    note: null,
  },
  {
    slug: "garmon-garmon",
    name: "Garmón",
    bodega: "GARMÓN",
    location: "Olivares de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 25.75,
    note: null,
  },
  {
    slug: "antidoto-antidoto",
    name: "Antídoto",
    bodega: "ANTÍDOTO",
    location: "San Esteban de Gormaz / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 11.5,
    note: null,
  },
  {
    slug: "antidoto-antidoto-magnum",
    name: "Antídoto Magnum",
    bodega: "ANTÍDOTO",
    location: "San Esteban de Gormaz / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 23.5,
    note: null,
  },
  {
    slug: "antidoto-la-hormiga",
    name: "La Hormiga",
    bodega: "ANTÍDOTO",
    location: "San Esteban de Gormaz / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 19.75,
    note: null,
  },
  {
    slug: "antidoto-roselito-rosado",
    name: "Roselito Rosado",
    bodega: "ANTÍDOTO",
    location: "San Esteban de Gormaz / Soria",
    region: "RIBERA DEL DUERO",
    category: "Rosado",
    price: 8.25,
    note: null,
  },
  {
    slug: "dominio-de-es-dominio-de-es-vinas-viejas-de-soria",
    name: "Dominio de Es Viñas Viejas de Soria",
    bodega: "DOMINIO DE ES",
    location: "San Esteban de Gormaz / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 54.0,
    note: null,
  },
  {
    slug: "bosque-de-matasnos-bosque-de-matasnos",
    name: "Bosque de Matasnos",
    bodega: "BOSQUE de MATASNOS",
    location: "Peñaranda de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 22.95,
    note: null,
  },
  {
    slug: "bosque-de-matasnos-bosque-de-matasnos-edicion-especial",
    name: "Bosque de Matasnos Edición Especial",
    bodega: "BOSQUE de MATASNOS",
    location: "Peñaranda de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 30.9,
    note: null,
  },
  {
    slug: "lopez-cristobal-lopez-cristobal-roble",
    name: "López Cristóbal Roble",
    bodega: "LÓPEZ CRISTÓBAL",
    location: "Roa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 6.5,
    note: null,
  },
  {
    slug: "lopez-cristobal-lopez-cristobal-crianza",
    name: "López Cristóbal Crianza",
    bodega: "LÓPEZ CRISTÓBAL",
    location: "Roa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 13.3,
    note: null,
  },
  {
    slug: "lopez-cristobal-lopez-cristobal-parcela-1",
    name: "López Cristóbal Parcela 1",
    bodega: "LÓPEZ CRISTÓBAL",
    location: "Roa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 20.5,
    note: null,
  },
  {
    slug: "lopez-cristobal-bagus",
    name: "Bagus",
    bodega: "LÓPEZ CRISTÓBAL",
    location: "Roa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 26.25,
    note: null,
  },
  {
    slug: "lagar-de-isilla-lagar-de-isilla-122-dias",
    name: "Lagar de Isilla 122 días",
    bodega: "LAGAR DE ISILLA",
    location: "Aranda de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 6.8,
    note: null,
  },
  {
    slug: "lagar-de-isilla-lagar-de-isilla-gestacion",
    name: "Lagar de Isilla Gestación",
    bodega: "LAGAR DE ISILLA",
    location: "Aranda de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 9.75,
    note: null,
  },
  {
    slug: "lagar-de-isilla-lagar-de-isilla-crianza",
    name: "Lagar de Isilla Crianza",
    bodega: "LAGAR DE ISILLA",
    location: "Aranda de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 11.5,
    note: null,
  },
  {
    slug: "dominio-de-cair-cair-cuvee",
    name: "Cair Cuvee",
    bodega: "DOMINIO DE CAIR",
    location: "La Aguilera / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Espumoso",
    price: 8.2,
    note: null,
  },
  {
    slug: "dominio-de-cair-cair-seleccion-la-aguilera",
    name: "Cair Selección La Aguilera",
    bodega: "DOMINIO DE CAIR",
    location: "La Aguilera / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 13.6,
    note: null,
  },
  {
    slug: "cepa-21-hito",
    name: "Hito",
    bodega: "CEPA 21",
    location: "Castrillo de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 7.86,
    note: "11 botellas + 1 bot. sin cargo",
  },
  {
    slug: "cepa-21-cepa-21",
    name: "Cepa 21",
    bodega: "CEPA 21",
    location: "Castrillo de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 14.4,
    note: "11 botellas + 1 bot. sin cargo",
  },
  {
    slug: "cepa-21-malabrigo",
    name: "Malabrigo",
    bodega: "CEPA 21",
    location: "Castrillo de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 24.65,
    note: null,
  },
  {
    slug: "dehesa-de-los-canonigos-quinta-generacion",
    name: "Quinta Generación",
    bodega: "DEHESA DE LOS CANÓNIGOS",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 8.0,
    note: null,
  },
  {
    slug: "dehesa-de-los-canonigos-dehesa-de-los-canonigos-crianza",
    name: "Dehesa de los Canónigos Crianza",
    bodega: "DEHESA DE LOS CANÓNIGOS",
    location: "Pesquera de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 14.95,
    note: null,
  },
  {
    slug: "dominio-de-atauta-viridiana-roble",
    name: "Viridiana Roble",
    bodega: "DOMINIO DE ATAUTA",
    location: "Atauta / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 5.85,
    note: null,
  },
  {
    slug: "dominio-de-atauta-la-celestina",
    name: "La Celestina",
    bodega: "DOMINIO DE ATAUTA",
    location: "Atauta / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 9.0,
    note: "11 botellas + 1 s/c",
  },
  {
    slug: "dominio-de-atauta-la-celestina-vendimia-seleccionada-reserva",
    name: "La Celestina Vendimia Seleccionada Reserva",
    bodega: "DOMINIO DE ATAUTA",
    location: "Atauta / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 11.75,
    note: "11 botellas + 1 s/C",
  },
  {
    slug: "dominio-de-atauta-parada-de-atauta",
    name: "Parada de Atauta",
    bodega: "DOMINIO DE ATAUTA",
    location: "Atauta / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 12.95,
    note: null,
  },
  {
    slug: "dominio-de-atauta-dominio-de-atauta",
    name: "Dominio de Atauta",
    bodega: "DOMINIO DE ATAUTA",
    location: "Atauta / Soria",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 22.5,
    note: null,
  },
  {
    slug: "el-canto-de-la-alondra-el-canto-de-la-alondra",
    name: "El Canto de la Alondra",
    bodega: "EL CANTO DE LA ALONDRA",
    location: "Valbuena de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 30.75,
    note: null,
  },
  {
    slug: "el-canto-de-la-alondra-el-sueno-de-la-alondra",
    name: "El Sueño de la Alondra",
    bodega: "EL CANTO DE LA ALONDRA",
    location: "Valbuena de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "finca-villacreces-pruno",
    name: "Pruno",
    bodega: "FINCA VILLACRECES",
    location: "Quintanilla de Onésimo / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 7.75,
    note: null,
  },
  {
    slug: "pago-de-los-capellanes-pago-de-los-capellanes-roble",
    name: "Pago de los Capellanes Roble",
    bodega: "PAGO DE LOS CAPELLANES",
    location: "Pedrosa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 9.3,
    note: null,
  },
  {
    slug: "pago-de-los-capellanes-pago-de-los-capellanes-crianza",
    name: "Pago de los Capellanes Crianza",
    bodega: "PAGO DE LOS CAPELLANES",
    location: "Pedrosa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 18.0,
    note: null,
  },
  {
    slug: "pago-de-los-capellanes-un-sueno-en-las-alturas",
    name: "Un Sueño en las alturas",
    bodega: "PAGO DE LOS CAPELLANES",
    location: "Pedrosa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 33.2,
    note: null,
  },
  {
    slug: "pago-de-los-capellanes-parcela-el-nogal",
    name: "Parcela El Nogal",
    bodega: "PAGO DE LOS CAPELLANES",
    location: "Pedrosa de Duero / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 39.25,
    note: null,
  },
  {
    slug: "pago-de-carraovejas-alma-carraovejas-pago-de-carraovejas",
    name: "Pago de Carraovejas",
    bodega: "PAGO DE CARRAOVEJAS -ALMA CARRAOVEJAS-",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "pago-de-carraovejas-alma-carraovejas-el-anejon",
    name: "El Anejón",
    bodega: "PAGO DE CARRAOVEJAS -ALMA CARRAOVEJAS-",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "pago-de-carraovejas-alma-carraovejas-cuesta-de-las-liebres",
    name: "Cuesta de las Liebres",
    bodega: "PAGO DE CARRAOVEJAS -ALMA CARRAOVEJAS-",
    location: "Peñafiel / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "bodega-milsetentayseis-alma-carraovejas-milsetentayseis",
    name: "Milsetentayseis",
    bodega: "BODEGA MILSETENTAYSEIS -ALMA CARRAOVEJAS-",
    location: "Fuentenebro / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 38.95,
    note: null,
  },
  {
    slug: "bodega-tresmano-proventus",
    name: "Proventus",
    bodega: "BODEGA TRESMANO",
    location: "Padilla de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 14.75,
    note: null,
  },
  {
    slug: "bodega-tresmano-tresmano",
    name: "Tresmano",
    bodega: "BODEGA TRESMANO",
    location: "Padilla de Duero / Valladolid",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 23.5,
    note: null,
  },
  {
    slug: "bodegas-pradorey-pradorey-el-miron-10-meses-barrica",
    name: "Pradorey El Mirón 10 meses barrica",
    bodega: "BODEGAS PRADOREY",
    location: "Gumiel de Mercado / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 8.57,
    note: "5 botellas + 1 bot. sin cargo",
  },
  {
    slug: "bodegas-pradorey-pradorey-valdelayegua-crianza",
    name: "Pradorey Valdelayegua Crianza",
    bodega: "BODEGAS PRADOREY",
    location: "Gumiel de Mercado / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 9.5,
    note: null,
  },
  {
    slug: "bodegas-pradorey-adaro",
    name: "Adaro",
    bodega: "BODEGAS PRADOREY",
    location: "Gumiel de Mercado / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 13.0,
    note: null,
  },
  {
    slug: "vina-sastre-vina-sastre-rafael-sastre-roble",
    name: "Viña Sastre Rafael Sastre Roble",
    bodega: "VIÑA SASTRE",
    location: "La Horra / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 7.25,
    note: null,
  },
  {
    slug: "vina-sastre-vina-sastre-crianza",
    name: "Viña Sastre Crianza",
    bodega: "VIÑA SASTRE",
    location: "La Horra / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 14.15,
    note: null,
  },
  {
    slug: "vina-sastre-vina-sastre-pago-de-santa-cruz",
    name: "Viña Sastre Pago de Santa Cruz",
    bodega: "VIÑA SASTRE",
    location: "La Horra / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 35.75,
    note: null,
  },
  {
    slug: "vina-sastre-vina-sastre-regina-vides",
    name: "Viña Sastre Regina Vides",
    bodega: "VIÑA SASTRE",
    location: "La Horra / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 47.5,
    note: null,
  },
  {
    slug: "vina-sastre-vina-sastre-pesus",
    name: "Viña Sastre Pesus",
    bodega: "VIÑA SASTRE",
    location: "La Horra / Burgos",
    region: "RIBERA DEL DUERO",
    category: "Tinto",
    price: 228.0,
    note: null,
  },
  {
    slug: "bodegas-aiurri-alma-carraovejas-landua",
    name: "Landua",
    bodega: "BODEGAS AIURRI -ALMA CARRAOVEJAS-",
    location: "Leza / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 14.1,
    note: null,
  },
  {
    slug: "bodegas-aiurri-alma-carraovejas-aiurri",
    name: "Aiurri",
    bodega: "BODEGAS AIURRI -ALMA CARRAOVEJAS-",
    location: "Leza / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 26.95,
    note: null,
  },
  {
    slug: "sierra-cantabria-sierra-cantabria-crianza",
    name: "Sierra Cantabria Crianza",
    bodega: "SIERRA CANTABRIA",
    location: "San Vicente de la Sonsierra / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "sierra-cantabria-san-vicente",
    name: "San Vicente",
    bodega: "SIERRA CANTABRIA",
    location: "San Vicente de la Sonsierra / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "sierra-cantabria-el-puntido",
    name: "El Puntido",
    bodega: "SIERRA CANTABRIA",
    location: "San Vicente de la Sonsierra / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "luis-canas-luis-canas-crianza",
    name: "Luis Cañas Crianza",
    bodega: "LUIS CAÑAS",
    location: "Villabuena de Álava / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 7.95,
    note: null,
  },
  {
    slug: "martinez-lacuesta-martinez-lacuesta-selecto-crianza",
    name: "Martínez Lacuesta Selecto Crianza",
    bodega: "MARTÍNEZ LACUESTA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 5.96,
    note: "11 botellas + 1 s/c",
  },
  {
    slug: "martinez-lacuesta-martinez-lacuesta-crianza",
    name: "Martínez Lacuesta Crianza",
    bodega: "MARTÍNEZ LACUESTA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 7.6,
    note: null,
  },
  {
    slug: "martinez-lacuesta-martinez-lacuesta-hinia",
    name: "Martínez Lacuesta Hinia",
    bodega: "MARTÍNEZ LACUESTA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 12.9,
    note: null,
  },
  {
    slug: "martinez-lacuesta-vermut-lacuesta-rojo",
    name: "Vermut Lacuesta Rojo",
    bodega: "MARTÍNEZ LACUESTA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Otros",
    price: 5.7,
    note: null,
  },
  {
    slug: "martinez-lacuesta-vermut-lacuesta-reserva",
    name: "Vermut Lacuesta Reserva",
    bodega: "MARTÍNEZ LACUESTA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Otros",
    price: 10.45,
    note: null,
  },
  {
    slug: "martinez-lacuesta-vermut-conzia",
    name: "Vermut Conzia",
    bodega: "MARTÍNEZ LACUESTA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Otros",
    price: 26.4,
    note: null,
  },
  {
    slug: "remelluri-lindes-de-remelluri",
    name: "Lindes de Remelluri",
    bodega: "REMELLURI",
    location: "Labastida / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 11.5,
    note: null,
  },
  {
    slug: "remelluri-remelluri-reserva",
    name: "Remelluri Reserva",
    bodega: "REMELLURI",
    location: "Labastida / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 18.5,
    note: null,
  },
  {
    slug: "marques-de-caceres-marques-de-caceres-crianza",
    name: "Marqués de Cáceres Crianza",
    bodega: "MARQUÉS DE CÁCERES",
    location: "Cenicero / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 5.95,
    note: "30 bot. + 6 bot. s/c - 72 bot.+ 18 bot. s/c",
  },
  {
    slug: "marques-de-caceres-marques-de-caceres-reserva",
    name: "Marqués de Cáceres Reserva",
    bodega: "MARQUÉS DE CÁCERES",
    location: "Cenicero / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 8.85,
    note: null,
  },
  {
    slug: "marques-de-caceres-gaudium",
    name: "Gaudium",
    bodega: "MARQUÉS DE CÁCERES",
    location: "Cenicero / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 29.75,
    note: null,
  },
  {
    slug: "marques-de-riscal-arienzo-crianza",
    name: "Arienzo Crianza",
    bodega: "MARQUÉS DE RISCAL",
    location: "Elciego / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 4.59,
    note: null,
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-reserva",
    name: "Marqués de Riscal Reserva",
    bodega: "MARQUÉS DE RISCAL",
    location: "Elciego / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 14.24,
    note: "11 bot. + 1 bot. sin cargo",
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-xr",
    name: "Marqués de Riscal XR",
    bodega: "MARQUÉS DE RISCAL",
    location: "Elciego / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 17.51,
    note: "11 bot. + 1 bot.sin cargo",
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-gran-reserva",
    name: "Marqués de Riscal Gran Reserva",
    bodega: "MARQUÉS DE RISCAL",
    location: "Elciego / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 38.25,
    note: "11 bot. + 1 bot.sin cargo",
  },
  {
    slug: "marques-de-riscal-baron-de-chirel",
    name: "Barón de Chirel",
    bodega: "MARQUÉS DE RISCAL",
    location: "Elciego / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 71.42,
    note: null,
  },
  {
    slug: "marques-de-murrieta-marques-de-murrieta",
    name: "Marqués de Murrieta",
    bodega: "MARQUÉS DE MURRIETA",
    location: "Logroño / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 18.0,
    note: null,
  },
  {
    slug: "marques-de-murrieta-dalmau",
    name: "Dalmau",
    bodega: "MARQUÉS DE MURRIETA",
    location: "Logroño / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 140.0,
    note: null,
  },
  {
    slug: "marques-de-murrieta-castillo-de-ygay",
    name: "Castillo de Ygay",
    bodega: "MARQUÉS DE MURRIETA",
    location: "Logroño / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 181.0,
    note: null,
  },
  {
    slug: "marques-de-murrieta-capellania-reserva-blanco",
    name: "Capellanía Reserva Blanco",
    bodega: "MARQUÉS DE MURRIETA",
    location: "Logroño / La Rioja",
    region: "RIOJA",
    category: "Blanco",
    price: 54.0,
    note: null,
  },
  {
    slug: "bodegas-izadi-izadi-crianza",
    name: "Izadi Crianza",
    bodega: "BODEGAS IZADI",
    location: "Villabuena de Álava / Álava",
    region: "RIOJA",
    category: "Tinto",
    price: 6.75,
    note: null,
  },
  {
    slug: "roda-sela",
    name: "Sela",
    bodega: "RODA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 12.1,
    note: null,
  },
  {
    slug: "roda-roda-reserva",
    name: "Roda Reserva",
    bodega: "RODA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 21.0,
    note: null,
  },
  {
    slug: "roda-roda-i-reserva",
    name: "Roda I Reserva",
    bodega: "RODA",
    location: "Haro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 34.5,
    note: null,
  },
  {
    slug: "j-palacios-remondo-la-montesa",
    name: "La Montesa",
    bodega: "J. PALACIOS REMONDO",
    location: "Alfaro / La Rioja",
    region: "RIOJA",
    category: "Tinto",
    price: 11.95,
    note: null,
  },
  {
    slug: "jose-pariente-jose-pariente-verdejo",
    name: "José Pariente Verdejo",
    bodega: "JOSÉ PARIENTE",
    location: "La Seca / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 7.25,
    note: "11 bot. + 1 bot. s/c",
  },
  {
    slug: "jose-pariente-las-fincas-de-jose-pariente",
    name: "Las Fincas de José Pariente",
    bodega: "JOSÉ PARIENTE",
    location: "La Seca / Valladolid",
    region: "RUEDA",
    category: "Tinto",
    price: 13.3,
    note: null,
  },
  {
    slug: "jose-pariente-finca-la-medina",
    name: "Finca La Medina",
    bodega: "JOSÉ PARIENTE",
    location: "La Seca / Valladolid",
    region: "RUEDA",
    category: "Tinto",
    price: 21.25,
    note: null,
  },
  {
    slug: "jose-pariente-finca-las-comas",
    name: "Finca Las Comas",
    bodega: "JOSÉ PARIENTE",
    location: "La Seca / Valladolid",
    region: "RUEDA",
    category: "Tinto",
    price: 29.25,
    note: null,
  },
  {
    slug: "castelo-de-medina-castelo-de-medina-verdejo",
    name: "Castelo de Medina Verdejo",
    bodega: "CASTELO DE MEDINA",
    location: "Villaverde de Medina / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 4.95,
    note: null,
  },
  {
    slug: "castelo-de-medina-castelo-de-medina-sauvignon-blanc",
    name: "Castelo de Medina Sauvignon Blanc",
    bodega: "CASTELO DE MEDINA",
    location: "Villaverde de Medina / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 5.75,
    note: null,
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-vina-calera",
    name: "Marqués de Riscal Viña Calera",
    bodega: "MARQUÉS DE RISCAL",
    location: "Rueda / Valladolid",
    region: "RUEDA",
    category: "Tinto",
    price: 3.28,
    note: null,
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-verdejo",
    name: "Marqués de Riscal Verdejo",
    bodega: "MARQUÉS DE RISCAL",
    location: "Rueda / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 7.39,
    note: "11 bot. + 1 bot. sin cargo",
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-verdejo-lias",
    name: "Marques de Riscal Verdejo Lías",
    bodega: "MARQUÉS DE RISCAL",
    location: "Rueda / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 7.63,
    note: "11 bot. + 1 bot. sin cargo",
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-sauvignon",
    name: "Marqués de Riscal Sauvignon",
    bodega: "MARQUÉS DE RISCAL",
    location: "Rueda / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 8.41,
    note: null,
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-finca-montico",
    name: "Marqués de Riscal Finca Montico",
    bodega: "MARQUÉS DE RISCAL",
    location: "Rueda / Valladolid",
    region: "RUEDA",
    category: "Tinto",
    price: 10.61,
    note: "11 bot. + 1 bot.sin cargo",
  },
  {
    slug: "marques-de-riscal-marques-de-riscal-limousin",
    name: "Marqués de Riscal Limousin",
    bodega: "MARQUÉS DE RISCAL",
    location: "Rueda / Valladolid",
    region: "RUEDA",
    category: "Tinto",
    price: 12.92,
    note: null,
  },
  {
    slug: "marques-de-caceres-marques-de-caceres-verdejo",
    name: "Marqués de Cáceres Verdejo",
    bodega: "MARQUÉS de CÁCERES",
    location: "Serrada / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 4.45,
    note: "30 bot. + 6 bot. sin cargo",
  },
  {
    slug: "martue-vinedos-de-nieva-blanco-nieva-verdejo",
    name: "Blanco Nieva Verdejo",
    bodega: "MARTUE VIÑEDOS DE NIEVA",
    location: "Nieva / Segovia",
    region: "RUEDA",
    category: "Blanco",
    price: 4.7,
    note: null,
  },
  {
    slug: "martue-vinedos-de-nieva-blanco-nieva-pie-franco",
    name: "Blanco Nieva Pie Franco",
    bodega: "MARTUE VIÑEDOS DE NIEVA",
    location: "Nieva / Segovia",
    region: "RUEDA",
    category: "Blanco",
    price: 8.5,
    note: null,
  },
  {
    slug: "bodegas-protos-protos-verdejo",
    name: "Protos Verdejo",
    bodega: "BODEGAS PROTOS",
    location: "La Seca / Valladolid",
    region: "RUEDA",
    category: "Blanco",
    price: 4.95,
    note: null,
  },
  {
    slug: "ossian-vides-y-vinos-alma-carraovejas-ossian",
    name: "Ossian",
    bodega: "OSSIAN VIDES y VINOS -ALMA CARRAOVEJAS-",
    location: "Nieva / Segovia",
    region: "VINOS DE LA TIERRA DE CASTILLA Y LEÓN",
    category: "Tinto",
    price: 23.5,
    note: null,
  },
  {
    slug: "ossian-vides-y-vinos-alma-carraovejas-capitel",
    name: "Capitel",
    bodega: "OSSIAN VIDES y VINOS -ALMA CARRAOVEJAS-",
    location: "Nieva / Segovia",
    region: "VINOS DE LA TIERRA DE CASTILLA Y LEÓN",
    category: "Tinto",
    price: 82.5,
    note: null,
  },
  {
    slug: "bodegas-mauro-mauro",
    name: "Mauro",
    bodega: "BODEGAS MAURO",
    location: "Tudela de Duero / Valladolid",
    region: "VINOS DE LA TIERRA DE CASTILLA Y LEÓN",
    category: "Tinto",
    price: 25.5,
    note: null,
  },
  {
    slug: "bodegas-mauro-mauro-vendimia-seleccionada",
    name: "Mauro Vendimia Seleccionada",
    bodega: "BODEGAS MAURO",
    location: "Tudela de Duero / Valladolid",
    region: "VINOS DE LA TIERRA DE CASTILLA Y LEÓN",
    category: "Tinto",
    price: 49.5,
    note: null,
  },
  {
    slug: "bodegas-habla-habla-del-silencio",
    name: "Habla del Silencio",
    bodega: "BODEGAS HABLA",
    location: "Trujillo / Cáceres",
    region: "VINOS DE LA TIERRA DE EXTREMADURA",
    category: "Tinto",
    price: 8.15,
    note: null,
  },
  {
    slug: "bodegas-habla-habla-de-ti",
    name: "Habla de Ti",
    bodega: "BODEGAS HABLA",
    location: "Trujillo / Cáceres",
    region: "VINOS DE LA TIERRA DE EXTREMADURA",
    category: "Tinto",
    price: 7.25,
    note: null,
  },
  {
    slug: "bodegas-habla-habla-malbec",
    name: "Habla Malbec",
    bodega: "BODEGAS HABLA",
    location: "Trujillo / Cáceres",
    region: "VINOS DE LA TIERRA DE EXTREMADURA",
    category: "Tinto",
    price: 18.75,
    note: null,
  },
  {
    slug: "bodegas-habla-habla-syrah",
    name: "Habla Syrah",
    bodega: "BODEGAS HABLA",
    location: "Trujillo / Cáceres",
    region: "VINOS DE LA TIERRA DE EXTREMADURA",
    category: "Tinto",
    price: 18.75,
    note: null,
  },
  {
    slug: "bodegas-villa-iulia-v-t-castilla-mota-del-cuervo-cuenca-villa-iulia-rosado-cabernet",
    name: "Villa Iulia Rosado Cabernet",
    bodega: "BODEGAS VILLA IULIA (V.T. CASTILLA) Mota del Cuervo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Rosado",
    price: 7.75,
    note: null,
  },
  {
    slug: "bodegas-villa-iulia-v-t-castilla-mota-del-cuervo-cuenca-villa-iulia-tempranillo-syrah",
    name: "Villa Iulia Tempranillo Syrah",
    bodega: "BODEGAS VILLA IULIA (V.T. CASTILLA) Mota del Cuervo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 7.75,
    note: null,
  },
  {
    slug: "bodegas-villa-iulia-v-t-castilla-mota-del-cuervo-cuenca-villa-iulia-galea-13-meses",
    name: "Villa Iulia Galea 13 meses",
    bodega: "BODEGAS VILLA IULIA (V.T. CASTILLA) Mota del Cuervo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 13.95,
    note: null,
  },
  {
    slug: "bodegas-villa-iulia-v-t-castilla-mota-del-cuervo-cuenca-villa-iulia-atia-sauvignon-blanc-8-meses",
    name: "Villa Iulia Atia Sauvignon Blanc 8 meses",
    bodega: "BODEGAS VILLA IULIA (V.T. CASTILLA) Mota del Cuervo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Blanco",
    price: 11.95,
    note: null,
  },
  {
    slug: "bodega-y-vinedos-illana-d-o-p-ribera-del-jucar-pozoamargo-cuenca-los-bobalistas-blanc-de-noir",
    name: "Los Bobalistas Blanc de Noir",
    bodega: "BODEGA Y VIÑEDOS ILLANA (D.O.P RIBERA DEL JUCAR) Pozoamargo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Blanco",
    price: 11.4,
    note: null,
  },
  {
    slug: "bodega-y-vinedos-illana-d-o-p-ribera-del-jucar-pozoamargo-cuenca-los-bobalistas-clasico-bobal",
    name: "Los Bobalistas Clásico Bobal",
    bodega: "BODEGA Y VIÑEDOS ILLANA (D.O.P RIBERA DEL JUCAR) Pozoamargo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 11.4,
    note: null,
  },
  {
    slug: "bodega-y-vinedos-illana-d-o-p-ribera-del-jucar-pozoamargo-cuenca-illana-10-meses",
    name: "Illana 10 meses",
    bodega: "BODEGA Y VIÑEDOS ILLANA (D.O.P RIBERA DEL JUCAR) Pozoamargo / Cuenca",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 8.6,
    note: null,
  },
  {
    slug: "ercavio-v-t-castilla-cabanas-de-yepes-toledo-el-senorito",
    name: "El Señorito",
    bodega: "ERCAVIO (V.T. CASTILLA) -Cabañas de Yepes / Toledo",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 11.65,
    note: null,
  },
  {
    slug: "ercavio-v-t-castilla-cabanas-de-yepes-toledo-la-plazuela",
    name: "La Plazuela",
    bodega: "ERCAVIO (V.T. CASTILLA) -Cabañas de Yepes / Toledo",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 27.95,
    note: null,
  },
  {
    slug: "seleccion-lucendo-v-t-castilla-valdepenas-ciudad-real-el-ultimo-lobo",
    name: "El Último Lobo",
    bodega: "SELECCIÓN LUCENDO (V.T. CASTILLA) -Valdepeñas / Ciudad Real",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 6.5,
    note: null,
  },
  {
    slug: "seleccion-lucendo-v-t-castilla-valdepenas-ciudad-real-el-linze-tinto-velasco-syrah",
    name: "El Linze Tinto Velasco -- Syrah",
    bodega: "SELECCIÓN LUCENDO (V.T. CASTILLA) -Valdepeñas / Ciudad Real",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 13.5,
    note: null,
  },
  {
    slug: "seleccion-lucendo-v-t-castilla-valdepenas-ciudad-real-el-linze-chardonnay-viogner",
    name: "El Linze Chardonnay -- Viogner",
    bodega: "SELECCIÓN LUCENDO (V.T. CASTILLA) -Valdepeñas / Ciudad Real",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Blanco",
    price: 13.5,
    note: null,
  },
  {
    slug: "blas-munoz-v-t-castilla-noblejas-toledo-blas-munoz-chardonnay-fermentado-en-barrica",
    name: "Blas Muñoz Chardonnay Fermentado en Barrica",
    bodega: "BLAS MUÑOZ (V.T. CASTILLA) --Noblejas / Toledo",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Blanco",
    price: 9.75,
    note: null,
  },
  {
    slug: "blas-munoz-v-t-castilla-noblejas-toledo-blas-munoz-cepas-viejas",
    name: "Blas Muñoz Cepas Viejas",
    bodega: "BLAS MUÑOZ (V.T. CASTILLA) --Noblejas / Toledo",
    location: null,
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 15.5,
    note: null,
  },
  {
    slug: "de-la-mata-de-la-mata-calleja-airen-sobre-lias",
    name: "De La Mata & Calleja Airén Sobre Lías",
    bodega: "DE LA MATA",
    location: "*&**** CALLEJA (V.T. CASTILLA) Corral de Almaguer / Toledo*",
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Blanco",
    price: 6.9,
    note: null,
  },
  {
    slug: "de-la-mata-de-la-mata-calleja-garnacha-tintorera-cencibel-y-syrah",
    name: "De la Mata & Calleja Garnacha Tintorera, Cencibel y Syrah",
    bodega: "DE LA MATA",
    location: "*&**** CALLEJA (V.T. CASTILLA) Corral de Almaguer / Toledo*",
    region: "MÁS VINOS DE CASTILLA LA MANCHA",
    category: "Tinto",
    price: 6.9,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-30-000-maravedies",
    name: "30.000 Maravedíes",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 13.5,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-30-000-maravedies-magnum",
    name: "30.000 Maravedíes Magnum",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 27.5,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-maranones",
    name: "Marañones",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 20.0,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-maranones-magnum",
    name: "Marañones Magnum",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 43.9,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-maranones-blanco-picarana-albillo-real",
    name: "Marañones Blanco Picarana Albillo Real",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Blanco",
    price: 21.7,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-maranones-pena-caballera-garnacha",
    name: "Marañones Peña Caballera Garnacha",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 25.4,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-maranones-pena-caballera-magnum",
    name: "Marañones Peña Caballera Magnum",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 55.0,
    note: null,
  },
  {
    slug: "bodega-maranones-alma-carraovejas-maranones-pena-cruzada-albillo-real",
    name: "Marañones Peña Cruzada Albillo Real",
    bodega: "BODEGA MARAÑONES --ALMA CARRAOVEJAS-",
    location: "Pelayos de la Presa / Madrid",
    region: "VINOS DE MADRID",
    category: "Tinto",
    price: 46.25,
    note: null,
  },
  {
    slug: "dominio-do-bibei-lalama",
    name: "Lalama",
    bodega: "DOMINIO DO BIBEI",
    location: "Manzaneda / Orense",
    region: "RIBEIRA SACRA",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "dominio-do-bibei-dominio-do-bibei",
    name: "Dominio do Bibei",
    bodega: "DOMINIO DO BIBEI",
    location: "Manzaneda / Orense",
    region: "RIBEIRA SACRA",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "valdesil-montenovo",
    name: "Montenovo",
    bodega: "VALDESIL",
    location: "Córgomo / Orense",
    region: "VALDEORRAS",
    category: "Tinto",
    price: 8.95,
    note: null,
  },
  {
    slug: "valdesil-valdesil-sobre-lias",
    name: "Valdesil Sobre Lías",
    bodega: "VALDESIL",
    location: "Córgomo / Orense",
    region: "VALDEORRAS",
    category: "Tinto",
    price: 14.95,
    note: null,
  },
  {
    slug: "o-luar-do-sil-luar-do-sil",
    name: "Luar do Sil",
    bodega: "O LUAR DO SIL",
    location: "Seadur / Orense",
    region: "VALDEORRAS",
    category: "Tinto",
    price: 9.15,
    note: null,
  },
  {
    slug: "o-luar-do-sil-luar-do-sil-sobre-lias",
    name: "Luar do Sil Sobre Lías",
    bodega: "O LUAR DO SIL",
    location: "Seadur / Orense",
    region: "VALDEORRAS",
    category: "Tinto",
    price: 13.5,
    note: null,
  },
  {
    slug: "bodega-san-roman-prima",
    name: "Prima",
    bodega: "BODEGA SAN ROMAN",
    location: "Pedrosa del Rey / Valladolid",
    region: "TORO",
    category: "Tinto",
    price: 8.3,
    note: null,
  },
  {
    slug: "bodega-san-roman-san-roman",
    name: "San Román",
    bodega: "BODEGA SAN ROMAN",
    location: "Pedrosa del Rey / Valladolid",
    region: "TORO",
    category: "Tinto",
    price: 23.5,
    note: null,
  },
  {
    slug: "teso-la-monja-almirez",
    name: "Almirez",
    bodega: "TESO LA MONJA",
    location: "Valdefinjas y Toro / Zamora",
    region: "TORO",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "teso-la-monja-victorino",
    name: "Victorino",
    bodega: "TESO LA MONJA",
    location: "Valdefinjas y Toro / Zamora",
    region: "TORO",
    category: "Tinto",
    price: null,
    note: null,
  },
  {
    slug: "alonso-del-yerro-paydos",
    name: "Paydos",
    bodega: "ALONSO del YERRO",
    location: "Toro / Zamora",
    region: "TORO",
    category: "Tinto",
    price: 25.5,
    note: null,
  },
  {
    slug: "bodegas-numanthia-numanthia",
    name: "Numanthia",
    bodega: "BODEGAS NUMANTHIA",
    location: "Valdefinjas / Zamora",
    region: "TORO",
    category: "Tinto",
    price: 39.5,
    note: null,
  },
  {
    slug: "bodegas-numanthia-termes",
    name: "Termes",
    bodega: "BODEGAS NUMANTHIA",
    location: "Valdefinjas / Zamora",
    region: "TORO",
    category: "Tinto",
    price: 19.3,
    note: null,
  },
  {
    slug: "elias-mora-elias-mora-vinas",
    name: "Elías Mora Viñas",
    bodega: "ELIAS MORA",
    location: "San Román de Hornija / Valladolid",
    region: "TORO",
    category: "Tinto",
    price: 6.35,
    note: null,
  },
  {
    slug: "gramona-gramona-imperial",
    name: "Gramona Imperial",
    bodega: "GRAMONA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 19.9,
    note: null,
  },
  {
    slug: "gramona-gramona-iii-lustros",
    name: "Gramona III Lustros",
    bodega: "GRAMONA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 27.35,
    note: null,
  },
  {
    slug: "gramona-vi-de-glass-riesling-gewurztraminer",
    name: "Vi de Glass Riesling / Gewürztraminer",
    bodega: "GRAMONA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 14.3,
    note: null,
  },
  {
    slug: "llopart-llopart-brut-nature",
    name: "Llopart Brut Nature",
    bodega: "LLOPART",
    location: "Subirats / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 11.8,
    note: null,
  },
  {
    slug: "llopart-llopart-integral-brut-nature",
    name: "Llopart Integral Brut Nature",
    bodega: "LLOPART",
    location: "Subirats / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 12.95,
    note: null,
  },
  {
    slug: "llopart-llopart-leopardi-brut-nature",
    name: "Llopart Leopardi Brut Nature",
    bodega: "LLOPART",
    location: "Subirats / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 20.3,
    note: null,
  },
  {
    slug: "llopart-llopart-rose-brut",
    name: "Llopart Rosé Brut",
    bodega: "LLOPART",
    location: "Subirats / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 12.95,
    note: null,
  },
  {
    slug: "llopart-llopart-microcosmico-rose-brut-nature",
    name: "Llopart Microcósmico Rosé Brut Nature",
    bodega: "LLOPART",
    location: "Subirats / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 16.75,
    note: null,
  },
  {
    slug: "recaredo-recaredo-terrers-gran-reserva-brut-nature",
    name: "Recaredo Terrers Gran Reserva Brut Nature",
    bodega: "RECAREDO",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 21.5,
    note: null,
  },
  {
    slug: "recaredo-reserva-particular",
    name: "Reserva Particular",
    bodega: "RECAREDO",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: null,
    note: null,
  },
  {
    slug: "agusti-torello-mata-kripta-kripta-reserva-brut",
    name: "Kripta Reserva Brut",
    bodega: "AGUSTÍ TORELLÓ MATA - KRIPTA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 8.9,
    note: null,
  },
  {
    slug: "agusti-torello-mata-kripta-kripta-iconic-gran-reserva-brut-nature",
    name: "Kripta Icónic Gran Reserva Brut Nature",
    bodega: "AGUSTÍ TORELLÓ MATA - KRIPTA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 14.35,
    note: null,
  },
  {
    slug: "agusti-torello-mata-kripta-kripta-trepat-rosado",
    name: "Kripta Trepat Rosado",
    bodega: "AGUSTÍ TORELLÓ MATA - KRIPTA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 10.5,
    note: null,
  },
  {
    slug: "agusti-torello-mata-kripta-kripta-brut-nature-gran-reserva",
    name: "Kripta Brut Nature Gran Reserva",
    bodega: "AGUSTÍ TORELLÓ MATA - KRIPTA",
    location: "Sant Sadurni d´Anoia / Barcelona",
    region: "CORPINNAT",
    category: "Espumoso",
    price: 47.5,
    note: null,
  },
  {
    slug: "a-o-c-champagne-moet-chandon-brut-imperial",
    name: "Möet & Chandon Brut Imperial",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 32.75,
    note: null,
  },
  {
    slug: "a-o-c-champagne-moet-chandon-brut-imperial-rose",
    name: "Möet & Chandon Brut Imperial Rosé",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 41.8,
    note: null,
  },
  {
    slug: "a-o-c-champagne-dom-perignon",
    name: "Dom Perignon",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 169.1,
    note: null,
  },
  {
    slug: "a-o-c-champagne-veuve-cliquot-brut",
    name: "Veuve Cliquot Brut",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 38.25,
    note: null,
  },
  {
    slug: "a-o-c-champagne-veuve-cliquot-brut-rose",
    name: "Veuve Cliquot Brut Rosé",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 44.65,
    note: null,
  },
  {
    slug: "a-o-c-champagne-ruinart-brut",
    name: "Ruinart Brut",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 44.25,
    note: null,
  },
  {
    slug: "a-o-c-champagne-ruinart-rose",
    name: "Ruinart Rosé",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 62.2,
    note: null,
  },
  {
    slug: "a-o-c-champagne-ruinart-blanc-de-blancs",
    name: "Ruinart Blanc de Blancs",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 66.95,
    note: null,
  },
  {
    slug: "a-o-c-champagne-laurent-perrier-la-cuvee-brut",
    name: "Laurent Perrier La Cuvee Brut",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 40.19,
    note: null,
  },
  {
    slug: "a-o-c-champagne-laurent-perrier-la-cuvee-rose",
    name: "Laurent Perrier La Cuvee Rose",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 71.8,
    note: null,
  },
  {
    slug: "a-o-c-champagne-laurent-perrier-ultra-brut",
    name: "Laurent Perrier Ultra Brut",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 58.4,
    note: null,
  },
  {
    slug: "a-o-c-champagne-laurent-perrier-millesime",
    name: "Laurent Perrier Millesimé",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 77.4,
    note: null,
  },
  {
    slug: "a-o-c-champagne-laurent-perrier-heritage",
    name: "Laurent Perrier Heritage",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 60.0,
    note: null,
  },
  {
    slug: "a-o-c-champagne-gran-siecle",
    name: "Gran Siecle",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 184.0,
    note: null,
  },
  {
    slug: "a-o-c-champagne-taittinger-brut-reserve",
    name: "Taittinger Brut Reserve",
    bodega: null,
    location: null,
    region: "A.O.C. CHAMPAGNE",
    category: "Espumoso",
    price: 37.5,
    note: null,
  },
  {
    slug: "otros-besame-semidulce",
    name: "Bésame Semidulce",
    bodega: null,
    location: null,
    region: "OTROS",
    category: "Tinto",
    price: 4.25,
    note: null,
  },
  {
    slug: "otros-esencia-27-semidulce",
    name: "Esencia 27 Semidulce",
    bodega: null,
    location: null,
    region: "OTROS",
    category: "Tinto",
    price: 4.4,
    note: "11 bot. + 1 bot. sin cargo",
  },
  {
    slug: "otros-sidra-trabanco-natural-cosecha-propia",
    name: "Sidra Trabanco Natural / Cosecha Propia",
    bodega: null,
    location: null,
    region: "OTROS",
    category: "Otros",
    price: null,
    note: null,
  },
];

export const REGIONS: string[] = [
  "VINOS DE PAGO",
  "ALMANSA",
  "BIERZO",
  "CALATAYUD",
  "CAMPO DE BORJA",
  "CIGALES",
  "JUMILLA",
  "MONTERREI",
  "RÍAS BAIXAS",
  "RIBEIRO",
  "RIBERA DEL DUERO",
  "RIOJA",
  "RUEDA",
  "VINOS DE LA TIERRA DE CASTILLA Y LEÓN",
  "VINOS DE LA TIERRA DE EXTREMADURA",
  "MÁS VINOS DE CASTILLA LA MANCHA",
  "VINOS DE MADRID",
  "RIBEIRA SACRA",
  "VALDEORRAS",
  "TORO",
  "CORPINNAT",
  "A.O.C. CHAMPAGNE",
  "OTROS",
];

export const CATEGORIES: WineCategory[] = ["Tinto", "Blanco", "Rosado", "Espumoso", "Otros"];

export const FEATURED_SLUGS: string[] = [
  "emilio-moro-emilio-moro",
  "protos-protos-reserva",
  "marques-de-riscal-marques-de-riscal-reserva",
  "roda-roda-reserva",
  "aalto-aalto",
  "marques-de-murrieta-marques-de-murrieta",
];

export const CATEGORY_IMAGE: Record<WineCategory, string> = {
  Tinto: tinto,
  Blanco: blanco,
  Rosado: rosado,
  Espumoso: blanco,
  Otros: reserva,
};
